baseURL = "/"
languageCode = "fi"
title = "Adaptive Audiovisual Solutions - AAS"


[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  google_analytics_id="UA-39007713-1"

  [params.homepage_meta_tags]
    meta_description = "AAS, Asiantuntijapalveluita ammattilaisten tarpeisiin vuosien kokemuksella."
    meta_og_title = "Adaptive Audiovisual Solutions - AAS"
    meta_og_type = "website"
    meta_og_url = "http://www.aas.fi"
    meta_og_image = "https://aas.fi/images/tb.png"
    meta_og_description = "AAS, Asiantuntijapalveluita ammattilaisten tarpeisiin monien vuosien kokemuksella."


[[menu.main]]
	name = "Palvelut"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Projektit"
    url = "/work/"
    weight = 2



[[menu.main]]
    name = "Historia"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Yhteydenotto"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
